### PR TITLE
feat: enable to add trusted_profile_ids as access group members

### PR DESCRIPTION
**Pull request by maheshwarishikha**
### Description

Enable to add trusted_profile_ids as access group members

Issue: [#10179](https://github.ibm.com/GoldenEye/issues/issues/10179)

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Enable to add trusted_profile_ids as access group members

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — DISMISSED** [review]

**Review by ocofaigh — COMMENTED** [review]
Oh @maheshwarishikha I guess we should also expose it in the submodule https://github.com/terraform-ibm-modules/terraform-ibm-iam-access-group/tree/main/modules/access-management (cc @MatthewLemmond )

**Review by ocofaigh — DISMISSED** [review]
can we be consistent with the default values. Some are `[]` and some are `null`

**Comment by maheshwarishikha** [comment]
> can we be consistent with the default values. Some are `[]` and some are `null`

@ocofaigh Referred some of the other modules and found that generally the default values used for
string - `null`
list - `[]`
map - `{}`
It is being used in the same way in this module too. So it can be considered as consistent.
Let me know if we still think to make changes... Thanks.

**Comment by ocofaigh** [comment]
@maheshwarishikha I meant consistent within this module. `admin_observability_ag_trusted_profile_ids` has a default value of `[]`, yet all others have `null`. Suggest to also set that one to null to match the others

**Review by akocbek — APPROVED** [review]

**Pull request merged**
